### ISSUE TITLE
Activity extension for favorites

### ISSUE THREAD

**Issue by PVince81** [owncloud-archive/metadata#3]
Trigger activities on favorite/unfavorite.
Add column in the activity page “send change notification only for favorited files/folders”

Extend `OCP\Activity\IExtension` for that.

CC @nickvergessen

**Comment by nickvergessen** [comment]
I could take care of this if you want me to

**Comment by PVince81** [comment]
That would be nice, thanks.
But first we need to get the basic work merged: https://github.com/owncloud/metadata/pull/2

**Comment by PVince81** [comment]
The main part of the favorites features has been merged in core: https://github.com/owncloud/core/pull/12360

**Comment by nickvergessen** [comment]
Btw, does this really make much sense?
I mean we can easily do this, but in most cases you know that just marked it as favorite.

De-favoriting may make sense, so you can find the file quickly again and then re-favorite it, but that's what undo actions should be for.

**Comment by nickvergessen** [comment]
We don't really want that, self actions are disabled by default anyway.
